version: "3.9"
services:
  chouquette-spa:
    container_name: chouquette-spa
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DISABLE_SENTY: 'true'
      GRAPHQL_URI: http://localhost:4000/graphql
      BROWSER_GRAPHQL_URI: http://localhost:4000/graphql
    volumes:
      - .:/usr/src/app
    entrypoint: yarn dev
