apiVersion: apps/v1
kind: Deployment
metadata:
  name: chouquette-spa-deployment
  labels:
      app: chouquette-spa
      environment: uat
      tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chouquette-spa
      environment: uat
  template:
    metadata:
      labels:
        app: chouquette-spa
        environment: uat
    spec:
      containers:
        - name: chouquette-spa
          image: docker.lachouquette.ch/chouquette-spa:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: development
            - name: GRAPHQL_URI
              value: http://api-gateway-deployment-service.default.svc.cluster.local:4000/graphql
            - name: RECAPTCHA_SITE_KEY
              value: 6LeGzZoUAAAAAMfFh3ybAsEBM_ocOUWbPnDRbg0U
            - name: MAILCHIMP_USER_ID
              value: 570ea90f4cbc136c450fe880a
            - name: MAILCHIMP_LIST_ID
              value: 26f7afd6a2
            - name: GOOGLE_MAPS_KEY
              value: AIzaSyCL4mYyxlnp34tnC57WyrU_63BJhuRoeKI