apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chouquette-spa-prod
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chouquette-spa-prod
                port:
                  number: 80
