apiVersion: apps/v1
kind: Deployment
metadata:
  name: chouquette-spa-uat
  labels:
      app: chouquette-spa
      environment: uat
      tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chouquette-spa
      environment: uat
  template:
    metadata:
      labels:
        app: chouquette-spa
        environment: uat
    spec:
      containers:
        - name: chouquette-spa-uat
          image: docker.lachouquette.ch/chouquette-spa-uat:latest
          command: ["yarn"]
          args: ["dev"]
          ports:
            - name: container-port
              containerPort: 3000
          startupProbe:
            httpGet:
              path: /
              port: container-port
            timeoutSeconds: 5
            failureThreshold: 8
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: container-port
            timeoutSeconds: 3
            failureThreshold: 3
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: chouquette-spa-uat
          env:
            - name: RECAPTCHA_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: chouquette-spa-uat
                  key: RECAPTCHA_SITE_KEY
            - name: MAILCHIMP_USER_ID
              valueFrom:
                secretKeyRef:
                  name: chouquette-spa-uat
                  key: MAILCHIMP_USER_ID
            - name: MAILCHIMP_LIST_ID
              valueFrom:
                secretKeyRef:
                  name: chouquette-spa-uat
                  key: MAILCHIMP_LIST_ID
            - name: GOOGLE_MAPS_KEY
              valueFrom:
                secretKeyRef:
                  name: chouquette-spa-uat
                  key: GOOGLE_MAPS_KEY
            - name: GRAPHQL_URI
              value: http://api-gateway-uat.default.svc.cluster.local:4000/graphql
            - name: BROWSER_GRAPHQL_URI
              value: https://api-gateway-uat.lachouquette.ch/graphql
