name: PROD - Continuous Deployment
on:
  release:
    types: [ released ]
jobs:
  update-uat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image and push to private repository
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: docker.lachouquette.ch/chouquette-spa-prod:${{ github.event.release.tag_name }},docker.lachouquette.ch/chouquette-spa-prod:latest
        env:
          NODE_ENV: production
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}