name: update-uat
on:
  push:
    branches:
      - api-gateway
jobs:
  update-uat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image and push to private repository
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: docker.lachouquette.ch/chouquette-spa:${{ github.sha }}
      - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Deploy image to cluster
        uses: ghostzero/kubectl@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/chouquette-spa-uat chouquette-spa-uat=docker.lachouquette.ch/chouquette-spa:${{ github.sha }} --record
      - name: Verify deployment
        uses: ghostzero/kubectl@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"rollout status deployment/chouquette-spa-uat"'
